[package]
version = "0.1.0"
name = "ab-rotation-program"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = { workspace = true }
ab-rotation-lib = { workspace = true }
